language: cpp
compiler:
- clang

dist: focal
os:
- linux

addons:
  sonarcloud:
    organization: "iainchesworth"
    token:
      secure: "BEwMb27/Wk30/ydyIeFwdPsqeN625chYQ2Or3qE4/g4Q6JYYNhBqIeXc3kLUPBfvvLCQPjxeIiXm7r369FonM5N+5/1eu54u6hWY+AZDgddMFF42yD7/cto3SP5uNve6ffGbsDbe2dTkGuVnDu1dzPiY+bVG4HUBSSgRlP0TxcrUcyR4QGJZIPosAh7XgxZyEII7q/V4EFvC3SBTmBrqJQnrgR02HM5aXK39ucNFnzFETXnHJl70tjadlkZNgH+ELJHvA8qLWiOeoehlZ+6k2+bUYjxGV8lLoghc2mFzTUl9uD46xY/n5gZ1tOQz0yiMkAv4rXVHVM93KCd0Dj8CRFVI+V44JiZZqgrT8r0P7/CGZuO8AVpXWYCO5deZcY/7261VhqNK14SZEEMPU6pVgFq0nEyq7sUkZXwC11mODmVe0oCd0GKNvw0kvc06r04F/VXoiEEgXctSFzykcd6+oE5NG9p8pYjCv6Jzlb8qy1/BbmCh+5FpXJQAcVGK4I8hT7HlC+k8Sr8i1dlKoAAP5LUBq1yntIMXL6h2lwQvquBAoLE608EA0Pw/dEFsMct40w5ikLnRb7PGYntkFD4qYUrxcnj2GcDctMkxWp1sC/dg9XXGCnl82Ul7cFiGiWy4J240DosyiETD7+JG1IbWCdb9LbBYZ6GYqg5WhAZtxfk="

before_install:
  # Prepare the build system
  - sudo apt-get update
  - sudo apt-get -qq -y --no-install-recommends install libicu66 libssl1.1
  - sudo env "PATH=$PATH" bash ./deps/paho.mqtt.sh
  - sudo apt -qq -y --no-install-recommends install ./deps/boost/boost-build_1.76.0_amd64.deb
  - git submodule update --init --recursive --jobs 8

script:
  - cmake -Bbuild -H.
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/

after_success:
  - NUMBER_OF_PROCESSORS=$(nproc --all)
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.cfamily.cache.enabled=true -Dsonar.cfamily.cache.path=${TRAVIS_HOME}/.cfamily -Dsonar.cfamily.threads=${NUMBER_OF_PROCESSORS}

cache:
  directories:
    - $HOME/.sonar/cache
    # This contains the CFamily cache. According to https://docs.travis-ci.com/user/caching/#pull-request-builds-and-caches,
    # for a PR, it will use the cache of the target branch if the branch of the PR does not already have its cache.
    - $HOME/.cfamily
