version: 1.0.0.{build}-{branch}
image: Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

environment:
  matrix:
    - GENERATOR: '"Visual Studio 16 2019" -A x86'
      BUILD_TYPE: Debug
    - GENERATOR: '"Visual Studio 16 2019" -A x86'
      BUILD_TYPE: Release
    - GENERATOR: '"Visual Studio 16 2019" -A x64'
      BUILD_TYPE: Debug
    - GENERATOR: '"Visual Studio 16 2019" -A x64'
      BUILD_TYPE: Release
      
install:
  - cmd: >-
  
     if "%platform%"=="x86" VCPKG_DEFAULT_TRIPLET=x86-windows
  
     if "%platform%"=="x64" VCPKG_DEFAULT_TRIPLET=x64-windows
  
     c:/tools/vcpkg install boost-algorithm boost-asio boost-beast boost-circular-buffer boost-log boost-json boost-program-options boost-property-tree boost-signals2 boost-system boost-thread boost-test boost-type-traits openssl paho-mqtt paho-mqttpp3[*]

cache:
  - c:/tools/vcpkg/installed -> appveyor.yml
  - c:/users/appveyor/appdata/local/vcpkg/archives -> appveyor.yml
  
before_build:
  - cmd: >-

      cd c:/projects/eagle-to-mqtt
      
      git submodule update --init --recursive --jobs 8

build_script:
  - cmd: >- 
  
      cd c:/projects/eagle-to-mqtt
  
      cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G%GENERATOR% -Bbuild -H.
  
      cmake --build build/ --config %BUILD_TYPE%

test_script:
  - cmd: >-
  
      cd c:/projects/eagle-to-mqtt/build/%BUILD_TYPE%
  
      tests/eagle-to-mqtt-tests.exe
