version: 1.0.{build}
image: Visual Studio 2019

environment:
  matrix:
    - GENERATOR: '"Visual Studio 16 2019" -A x64'
      BUILD_TYPE: Release
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

install:
  - cd c:\tools\vcpkg
  - vcpkg install boost:x64-windows boost-log:x64-windows boost-json:x64-windows boost-program-options:x64-windows openssl:x64-windows paho-mqtt:x64-windows paho-mqttpp3[*]:x64-windows

cache:
  - c:/tools/vcpkg/installed -> appveyor.yml
  
before_build:
  - cd c:/projects/eagle-to-mqtt
  - git submodule update --init --recursive --jobs 8

build_script:
  - cd c:/projects/eagle-to-mqtt
  - cmake -D CMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G %GENERATOR% -B build -H .
  - cmake --build build/ --config %BUILD_TYPE%

test_script:
  - cd c:/projects/eagle-to-mqtt/build/%BUILD_TYPE%
  - tests/eagle-to-mqtt-tests.exe
