#include "test_tools/test_tools_solarapi_generator.h"

std::string test_tools::SolarApi_Generator::Generate_CurrentData_Inverter_NonHybrid() const
{
    static const std::string PAYLOAD_CURRENTDATA_INVERTER =
    "{"
        "\"Body\" : {"
           "\"DAY_ENERGY\" : {"
              "\"Unit\" : \"Wh\","
              "\"Values\" : {"
                  "\"1\" : 14868,"
                  "\"2\" : 12345,"
                  "\"3\" : 54321"
              "}"
           "},"
           "\"PAC\" : {"
              "\"Unit\" : \"W\","
              "\"Values\" : {"
                  "\"1\" : 0,"
                  "\"2\" : 0,"
                  "\"3\" : 0"
              "}"
           "},"
           "\"TOTAL_ENERGY\" : {"
              "\"Unit\" : \"kWh\","
              "\"Values\" : {"
                  "\"1\" : 27803902,"
                  "\"2\" : 12345678,"
                  "\"3\" : 43214321"
              "}"
           "},"
           "\"YEAR_ENERGY\" : {"
              "\"Unit\" : \"kW\","
              "\"Values\" : {"
                  "\"1\" : 6692366,"
                  "\"2\" : 1234567,"
                  "\"3\" : 7654321"
              "}"
           "}"
        "},"
        "\"Head\" : {"
           "\"RequestArguments\" : {"
              "\"Query\" : \"Inverter\","
              "\"Scope\" : \"System\""
           "},"
           "\"Status\" : {"
              "\"Code\" : 0,"
              "\"Reason\" : \"\","
              "\"UserMessage\" : \"\""
           "},"
           "\"Timestamp\" : \"2021-07-14T17:11:58+10:00\""
        "}"
    "}";

    return PAYLOAD_CURRENTDATA_INVERTER;
}

std::string test_tools::SolarApi_Generator::Generate_CurrentData_PowerFlow_NonHybrid() const
{
    static const std::string PAYLOAD_CURRENTDATA_POWERFLOW =
    "{"
        "\"Body\" : {"
            "\"Inverters\" : {"
                "\"1\" : {"
                    "\"DT\" : 102,"
                    "\"E_Day\" : 1393.2000732421875 ,"
                    "\"E_Total\" : 1734796.125,"
                    "\"E_Year\" : 322593.5,"
                    "\"P\" : 88"
                "},"
                "\"2\" : {"
                    "\"DT\" : 86,"
                    "\"E_Day\" : 1618.5,"
                    "\"E_Total\" : 3026782,"
                    "\"E_Year\" : 385172.09375,"
                    "\"P\" : 104"
                "},"
                "\"3\" : {"
                    "\"DT\" : 106,"
                    "\"E_Day\" : 1695.800048828125 ,"
                    "\"E_Total\" : 3160499.75,"
                    "\"E_Year\" : 399904.09375,"
                    "\"P\" : 109"
                "},"
                "\"55\" : {"
                    "\"DT\" : 224,"
                    "\"E_Day\" : 1699,"
                    "\"E_Total\" : 3275219.75,"
                    "\"E_Year\" : 403993.21875,"
                    "\"P\" : 109"
                "}"
            "},"
            "\"Site\" : {"
                "\"E_Day\" : 6406.5001220703125 ,"
                "\"E_Total\" : 11197297.625,"
                "\"E_Year\" : 1511662.90625 ,"
                "\"Meter_Location\" : \"unknown\","
                "\"Mode\" : \"produce-only\","
                "\"P_Akku\" : null ,"
                "\"P_Grid\" : null ,"
                "\"P_Load\" : null ,"
                "\"P_PV\" : 410,"
                "\"rel_Autonomy\" : null ,"
                "\"rel_SelfConsumption\" : null"
            "},"
            "\"Version\" : \"12\""
        "},"
        "\"Head\" : {"
            "\"RequestArguments\" : {},"
            "\"Status\" : {"
                "\"Code\" : 0,"
                "\"Reason\" : \"\","
                "\"UserMessage\" : \"\""
            "},"
            "\"Timestamp\" : \"2019-06-12T15:31:08+02:00\""
        "}"
    "}";

    return PAYLOAD_CURRENTDATA_POWERFLOW;
}
