name: Build Application (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VCPKG_DIR: ${{github.workspace}}/deps/vcpkg
  VCPKG_DEFAULT_TRIPLET: x64-windows
  BUILD_DIR: ${{github.workspace}}/build-windows
  BUILD_TYPE: RelWithDebInfo
  BUILD_ARCHIVE: binaries-with-build-artefacts.zip
  BINARIES_ARCHIVE: binaries.zip

jobs:      

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

  #============================================================================
  #
  #  Configure any/all pre-requisites
  #
  #============================================================================

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install 3rd Party Dependencies
      shell: pwsh
      run: |
        # Core dependencies
        choco install 7zip ninja
        ${{env.VCPKG_DIR}}/bootstrap-vcpkg.bat
        ${{env.VCPKG_DIR}}/vcpkg integrate install

  #============================================================================
  #
  #  (All Platforms) Build the application
  #
  #============================================================================      

    - name: Cache vcpkg
      uses: actions/cache@v2
      with:
        path: |
          "${{env.VCPKG_DIR}}/buildtrees"
          "${{env.VCPKG_DIR}}/downloads"
          "${{env.VCPKG_DIR}}/packages"
          "${{env.VCPKG_DIR}}/vcpkg*"
          "${{env.BUILD_DIR}}/vcpkg_installed"
        key: ${{runner.os}}-build-${{env.cache-name}}-${{hashFiles('**/vcpkg.json')}}
        restore-keys: |
            ${{runner.os}}-build-${{env.cache-name}}-
            ${{runner.os}}-build-
            ${{runner.os}}-

    - name: Build Application
      run: |
        cmake -G Ninja -S ${{github.workspace}} -B ${{env.BUILD_DIR}} -DCMAKE_MAKE_PROGRAM=C:\ProgramData\chocolatey\bin\ninja.exe -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{env.VCPKG_DIR}}/scripts/buildsystems/vcpkg.cmake
        cmake --build ${{env.BUILD_DIR}} --parallel 4 --config ${{env.BUILD_TYPE}}

    - name: Archive Build Binaries
      run: |
        C:\ProgramData\chocolatey\bin\7z.exe a -tzip ${{runner.os}}-${{env.BUILD_ARCHIVE}} ${{env.BUILD_DIR}} -mx9 -mmt
        C:\ProgramData\chocolatey\bin\7z.exe a -tzip ${{runner.os}}-${{env.BINARIES_ARCHIVE}} ${{env.BUILD_DIR}}/eagle-to-mqtt.exe ${{env.BUILD_DIR}}/*.dll -mx9 -mmt

    - name: Upload Build Artefacts Archive
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: ${{runner.os}}-artefacts-buildlogs-testbinaries-and-coveragefiles
        path: ${{runner.os}}-${{env.BUILD_ARCHIVE}}
        if-no-files-found: warn

    - name: Upload Build Binaries Archive
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: ${{runner.os}}-binaries
        path: ${{runner.os}}-${{env.BINARIES_ARCHIVE}}
        if-no-files-found: error

  #============================================================================
  #
  #  Run the unit and integration tests
  #
  #============================================================================

    - name: Run Unit and Integration Tests
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir ${{env.BUILD_DIR}}
