name: eagle-to-mqtt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  job:
    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - name: windows-latest-cl
            os: windows-latest
            triplet: x64-windows
            cxx: cl.exe
            cc: cl.exe
            vcpkgCommitId: '1257354a3ab0bebd8abe95281ca561537853578c'
          - name: ubuntu-latest-clang
            os: ubuntu-latest
            triplet: x64-linux
            cxx: clang++
            cc: clang
            vcpkgCommitId: '1257354a3ab0bebd8abe95281ca561537853578c'
          - name: ubuntu-latest-gcc
            os: ubuntu-latest
            triplet: x64-osx
            cxx: g++
            cc: gcc
            vcpkgCommitId: '1257354a3ab0bebd8abe95281ca561537853578c'
          - name: macos-latest-clang
            os: macos-latest
            triplet: x64-osx
            cxx: clang++
            cc: clang
            vcpkgCommitId: '1257354a3ab0bebd8abe95281ca561537853578c'

    env:
      BUILD_DIR: '${{ github.workspace }}/build'

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup compiler environment

    - uses: ilammy/msvc-dev-cmd@latest
      if: "startsWith(matrix.name, 'windows')"
      with:
          arch: ${{ matrix.arch }}

    - uses: lukka/set-shell-env@latest
      with:
        CXX: ${{ matrix.cxx }}
        CC: ${{ matrix.cc }}

    - uses: egor-tensin/setup-gcc@v1
      if: "startsWith(matrix.name, 'ubuntu')"
      with:
        version: latest
        platform: x64
    
    - uses: lukka/get-cmake@latest
      
    - name: Build dependencies (via vcpkg)
      uses: lukka/run-vcpkg@main
      id: runvcpkg
      with:
        # Just install vcpkg for now, do not install any ports in this step yet.
        setupOnly: true
        # Location of the vcpkg submodule in the Git repository
        vcpkgDirectory: '${{ github.workspace }}/deps/vcpkg'
        vcpkgGitCommitId: '${{ matrix.vcpkgCommitId}}'
        # Ensure the cache key changes any time the content of the response file changes.
        appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
        vcpkgTriplet: ${{ matrix.triplet }}
        # Ensure the vcpkg artifacts are cached, they are generated in the 'CMAKE_BINARY_DIR/vcpkg_installed'.
        additionalCachedPaths: ${{ env.BUILD_DIR }}/vcpkg_installed

    - name: Build eagle-to-mqtt
      uses: lukka/run-cmake@main
      id: runcmake
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        buildDirectory: '${{ env.BUILD_DIR }}'
        useVcpkgToolchainFile: true
        cmakeAppendedArgs: '-B ${{github.workspace}}/build -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}'
        buildWithCMake: true
        buildWithCMakeArgs: '--config ${{env.BUILD_TYPE}} --parallel'

    - name: Run unit and integration tests
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
